import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/usr/bin/google-chrome', headless: true, args: ['--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1600, height: 1120 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', e => errors.push(e.message));
try {
  await page.goto('http://127.0.0.1:3000', { waitUntil: 'networkidle' });
  await page.getByText('API connected', { exact: true }).waitFor({ timeout: 20_000 });
  const demoResponsePromise = page.waitForResponse(r => r.url().endsWith('/api/demo') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Run local demo', exact: true }).click();
  const demoResponse = await demoResponsePromise;
  assert.equal(demoResponse.status(), 200, 'real POST demo returns success');
  const demoReport = await demoResponse.json();
  await page.locator('.run-id').getByText(demoReport.id, { exact: true }).waitFor();
  await page.getByText('Deterministic fixture plan', { exact: true }).waitFor({ timeout: 120_000 });
  await page.getByRole('button', { name: 'Run local demo', exact: true }).waitFor({ timeout: 120_000 });
  await page.getByText('Not a live AI result', { exact: true }).waitFor();
  await page.getByRole('heading', { name: 'Finding workbench' }).waitFor();
  assert.equal(await page.locator('.execution').count(), 2, 'base and head executions are visible');
  await page.screenshot({ path: '../docs/dashboard.png', fullPage: true });
  await page.getByRole('button', { name: 'Source citations', exact: false }).click();
  await page.getByText('Source citations validated', { exact: true }).waitFor();
  assert.ok(await page.locator('.citation-card').count() > 0);
  await page.getByRole('button', { name: 'Impact map', exact: true }).click();
  assert.ok(await page.getByRole('img', { name: /Impact graph/ }).count() > 0);
  await page.getByRole('button', { name: 'Probe plan', exact: true }).click();
  await page.getByRole('heading', { name: 'Declarative HTTP probe' }).waitFor();
  const search = page.getByRole('textbox', { name: 'Search findings' });
  await search.fill('no-such-probe-uniquely');
  await page.getByRole('heading', { name: 'No matching findings' }).waitFor();
  await page.getByRole('button', { name: 'Clear filters' }).click();
  await page.getByRole('button', { name: 'Execution traces' }).click();
  const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('link', { name: 'Export report' }).click()]);
  assert.match(download.suggestedFilename(), /^run-.*\.md$/);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: '.smoke-mobile.png', fullPage: true });
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  assert.equal(overflow, false, 'mobile page has no horizontal overflow');
  assert.deepEqual(errors, [], 'no browser JS errors');
  const refused = await page.request.post('http://127.0.0.1:3000/api/demo', { headers: { Origin: 'http://evil.example', 'Content-Type': 'application/json' }, data: '{}' });
  assert.equal(refused.status(), 403);
  const invalid = await page.request.get('http://127.0.0.1:3000/api/runs/run-invalid/report.json');
  assert.equal(invalid.status(), 404);
  console.log(JSON.stringify({ passed: true, checked: ['real demo publication', 'fixture provenance', 'base/head traces', 'citations', 'impact map', 'probe plan', 'search zero state', 'report download', 'mobile overflow', 'JS errors', 'cross-origin write denied', 'malformed report route denied'], screenshot: 'docs/dashboard.png', viewport: '1600×1120', mobile: '390×844' }, null, 2));
} finally { await browser.close(); }
